import Docker from 'dockerode'
import type McServer from '#models/mc_server'
import logger from '@adonisjs/core/services/logger'
import { mkdir, writeFile, access, readdir, stat } from 'node:fs/promises'
import { join } from 'node:path'
import { constants } from 'node:fs'
import type { Readable } from 'node:stream'
import http from 'node:http'
import https from 'node:https'

export interface ContainerRuntimeState {
  status: 'running' | 'stopped' | 'restarting' | 'error'
  containerId: string | null
  memoryLimitMb: number
  serverPort: number
}

export interface ContainerStatsSnapshot {
  online: boolean
  cpuPercent: number
  memoryUsageBytes: number
  memoryBytes: number
  memoryLimitBytes: number
  memoryPercent: number
  networkRxBytes: number
  networkTxBytes: number
  diskBytes: number
}

export default class McContainerService {
  protected docker: Docker

  constructor() {
    this.docker = new Docker(
      process.env.DOCKER_HOST
        ? undefined
        : process.platform === 'win32'
          ? { socketPath: '//./pipe/docker_engine' }
          : { socketPath: process.env.DOCKER_SOCKET_PATH || '/var/run/docker.sock' }
    )
  }

  protected getContainer(server: McServer): Docker.Container {
    return this.docker.getContainer(server.containerName)
  }

  /**
   * Get Docker engine version if accessible
   */
  async getDockerEngineVersion(): Promise<string | null> {
    try {
      const ping = await this.docker.ping()
      if (ping) {
        const ver = await this.docker.version()
        return ver.Version || null
      }
      return null
    } catch {
      return null
    }
  }

  /**
   * Check if container is running and return runtime state
   */
  async getContainerStatus(server: McServer): Promise<ContainerRuntimeState> {
    try {
      const container = this.getContainer(server)
      const inspect = await container.inspect()

      let status: ContainerRuntimeState['status'] = 'stopped'
      if (inspect.State.Running) {
        status = 'running'
      } else if (inspect.State.Restarting) {
        status = 'restarting'
      }

      return {
        status,
        containerId: inspect.Id,
        memoryLimitMb: server.maxMemoryMb,
        serverPort: server.serverPort,
      }
    } catch (error: any) {
      if (error?.statusCode === 404) {
        return {
          status: 'stopped',
          containerId: null,
          memoryLimitMb: server.maxMemoryMb,
          serverPort: server.serverPort,
        }
      }
      return {
        status: 'error',
        containerId: null,
        memoryLimitMb: server.maxMemoryMb,
        serverPort: server.serverPort,
      }
    }
  }

  /**
   * Start or create server container
   */
  async startContainer(server: McServer): Promise<void> {
    // 1. Ensure server data directory exists
    await mkdir(server.dataDirectory, { recursive: true })

    // 2. Check server executable jar
    const jarPath = join(server.dataDirectory, server.serverJar)
    try {
      await access(jarPath, constants.F_OK)
    } catch {
      throw new Error(
        `Server jar file "${server.serverJar}" not found in server directory. Please upload it first.`
      )
    }

    // 3. Ensure EULA agreement
    const eulaPath = join(server.dataDirectory, 'eula.txt')
    await writeFile(eulaPath, '# Generated by Pidan Panel\neula=true\n', 'utf8')

    // 4. Check if container already exists
    const container = this.getContainer(server)
    try {
      const inspect = await container.inspect()
      if (inspect.State.Running) {
        throw new Error('Server is already running.')
      }
      // Remove stopped container to ensure fresh launch configuration (ports, JVM flags, memory)
      await container.remove({ force: true })
    } catch (err: any) {
      if (err?.statusCode !== 404 && err.message !== 'Server is already running.') {
        throw err
      }
      if (err.message === 'Server is already running.') {
        throw err
      }
    }

    // 5. Ensure docker image is available locally
    await this.ensureImage(server.dockerImage)

    // 6. Create new container
    const newContainer = await this.docker.createContainer({
      name: server.containerName,
      Image: server.dockerImage,
      AttachStdin: true,
      AttachStdout: true,
      AttachStderr: true,
      OpenStdin: true,
      StdinOnce: false,
      Tty: true,
      WorkingDir: '/data',
      Cmd: ['java', ...server.jvmOptions, '-jar', server.serverJar, 'nogui'],
      HostConfig: {
        Binds: [`${server.dataDirectory}:/data`],
        PortBindings: {
          '25565/tcp': [{ HostPort: String(server.serverPort) }],
        },
        RestartPolicy: {
          Name: 'no',
        },
      },
      ExposedPorts: {
        '25565/tcp': {},
      },
    })

    await newContainer.start()
  }

  /**
   * Stop container gracefully, fallback to docker stop
   */
  async stopContainer(server: McServer, timeoutSeconds?: number): Promise<void> {
    const container = this.getContainer(server)
    const effectiveTimeout = Math.max(
      5,
      Math.min(300, timeoutSeconds ?? (server as any).stopTimeoutSeconds ?? 60)
    )

    try {
      const inspect = await container.inspect()
      if (!inspect.State.Running) {
        return
      }

      let sentStop = false
      try {
        await this.sendCommand(server, 'stop')
        sentStop = true
      } catch {
        // Fallback directly to container stop
      }

      if (sentStop) {
        // Wait for container to shut down naturally after /stop command
        const pollInterval = process.env.NODE_ENV === 'test' ? 50 : 1000
        const startTime = Date.now()
        while (Date.now() - startTime < effectiveTimeout * 1000) {
          await new Promise((r) => setTimeout(r, pollInterval))
          try {
            const currentInspect = await container.inspect()
            if (!currentInspect.State.Running) {
              return
            }
          } catch (err: any) {
            if (err?.statusCode === 404) return
            throw err
          }
        }
      }

      // If /stop failed or didn't exit within the grace period, trigger Docker container stop
      await container.stop({ t: 10 }).catch(() => {})
    } catch (err: any) {
      if (err?.statusCode === 404) {
        return
      }
      throw err
    }
  }

  /**
   * Forcefully kill the container immediately (SIGKILL)
   */
  async killContainer(server: McServer): Promise<void> {
    const container = this.getContainer(server)
    try {
      const inspect = await container.inspect()
      if (!inspect.State.Running) {
        return
      }
      await container.kill()
    } catch (err: any) {
      if (err?.statusCode === 404 || err?.statusCode === 409) {
        return
      }
      throw err
    }
  }

  /**
   * Restart container
   */
  async restartContainer(server: McServer): Promise<void> {
    await this.stopContainer(server)
    await this.startContainer(server)
  }

  /**
   * Send console command to running container standard input
   */
  async sendCommand(server: McServer, command: string): Promise<void> {
    const container = this.getContainer(server)
    const inspect = await container.inspect()
    if (!inspect.State.Running) {
      throw new Error('Cannot send command: server is not running.')
    }

    // Normalize command: strip leading slashes (e.g., "/help" -> "help") and whitespace
    const cleanCmd = command.trim().replace(/^\/+/, '')
    if (!cleanCmd) {
      return
    }

    const payload = `${cleanCmd}\n`

    await new Promise<void>((resolve, reject) => {
      const modem: any = this.docker.modem
      const optsf: any = {
        path: `/containers/${container.id}/attach?stream=1&stdin=1`,
        method: 'POST',
        headers: {
          Connection: 'Upgrade',
          Upgrade: 'tcp',
        },
      }

      if (modem.socketPath) {
        optsf.socketPath = modem.socketPath
      } else {
        optsf.hostname = modem.host
        optsf.port = modem.port
      }

      const transport = modem.protocol === 'https' || modem.protocol === 'https:' ? https : http
      const req = transport.request(optsf)

      let isSettled = false
      let timeoutTimer: NodeJS.Timeout | null = null

      const cleanup = () => {
        if (timeoutTimer) {
          clearTimeout(timeoutTimer)
          timeoutTimer = null
        }
      }

      const onError = (err: Error) => {
        if (!isSettled) {
          isSettled = true
          cleanup()
          reject(err)
        }
      }

      timeoutTimer = setTimeout(() => {
        if (!isSettled) {
          isSettled = true
          try {
            req.destroy(new Error('Timed out waiting to attach and send command to container.'))
          } catch {}
          reject(new Error('Command execution timed out.'))
        }
      }, 5000)

      req.once('error', onError)

      req.on('upgrade', (_res: any, socket: any) => {
        socket.once('error', onError)
        socket.write(payload, 'utf8', (writeErr: any) => {
          if (writeErr) {
            onError(writeErr)
            return
          }

          setTimeout(() => {
            if (!isSettled) {
              isSettled = true
              cleanup()
              try {
                socket.destroy()
              } catch {}
              resolve()
            }
          }, 80)
        })
      })

      // Flush HTTP headers immediately so Docker daemon receives the upgrade request without buffering
      req.flushHeaders()
    })
  }

  /**
   * Stream live container logs and historical crash logs
   */
  async streamLogs(server: McServer, onLine: (line: string) => void): Promise<() => void> {
    let isDisposed = false
    let currentLogStream: Readable | null = null
    let pollTimer: ReturnType<typeof setTimeout> | null = null
    let attachedContainerId: string | null = null

    const attachToContainer = async (
      container: Docker.Container,
      inspect: Docker.ContainerInspectInfo
    ) => {
      attachedContainerId = inspect.Id

      // 1. If container is not running, output historical crash / exit logs
      if (!inspect.State.Running) {
        try {
          const rawLogs = (await container.logs({
            stdout: true,
            stderr: true,
            tail: 100,
            follow: false,
          })) as unknown as Buffer | string

          const logContent = typeof rawLogs === 'string' ? rawLogs : rawLogs.toString('utf8')
          if (logContent.trim()) {
            const lines = logContent.split(/\r?\n/)
            for (const line of lines) {
              if (line) onLine(line)
            }
          }

          if (inspect.State.ExitCode !== 0) {
            onLine(
              `\x1b[31;1m[Panel] Container exited with code ${inspect.State.ExitCode}${inspect.State.Error ? ' (' + inspect.State.Error + ')' : ''}\x1b[0m`
            )
          } else {
            onLine('\x1b[33m[Panel] Server container is currently offline.\x1b[0m')
          }
        } catch {}
        return
      }

      // 2. If running, stream live output
      try {
        const stream = (await container.logs({
          follow: true,
          stdout: true,
          stderr: true,
          tail: 100,
        })) as unknown as Readable

        currentLogStream = stream

        let buffer = ''
        const onData = (chunk: Buffer | string) => {
          buffer += chunk.toString('utf8')
          const lines = buffer.split(/\r?\n/)
          buffer = lines.pop() || ''
          for (const line of lines) {
            onLine(line)
          }
        }

        stream.on('data', onData)
        stream.on('end', async () => {
          currentLogStream = null
          if (isDisposed) return

          const finalInspect = await container.inspect().catch(() => null)
          if (finalInspect && finalInspect.State.ExitCode !== 0) {
            onLine(
              `\x1b[31;1m[Panel] Container process exited with code ${finalInspect.State.ExitCode}${finalInspect.State.Error ? ' (' + finalInspect.State.Error + ')' : ''}\x1b[0m`
            )
          } else {
            onLine('\x1b[33m[Panel] Server container has stopped.\x1b[0m')
          }
        })

        stream.on('error', (err) => {
          if (!isDisposed) {
            onLine(`\x1b[31m[Panel] Log stream error: ${err.message}\x1b[0m`)
          }
        })
      } catch (err: any) {
        onLine(`\x1b[31m[Panel] Failed to attach to log stream: ${err.message}\x1b[0m`)
      }
    }

    const checkAndWatch = async () => {
      if (isDisposed) return

      try {
        const container = this.getContainer(server)
        const inspect = await container.inspect().catch(() => null)

        if (!inspect) {
          if (attachedContainerId !== null) {
            attachedContainerId = null
            onLine('\x1b[33m[Panel] Waiting for container to start...\x1b[0m')
          }
        } else {
          // Attach if new container or container started running
          if (inspect.Id !== attachedContainerId || (!currentLogStream && inspect.State.Running)) {
            if (currentLogStream) {
              currentLogStream.destroy()
              currentLogStream = null
            }
            await attachToContainer(container, inspect)
          }
        }
      } catch {}

      if (!isDisposed) {
        pollTimer = setTimeout(checkAndWatch, 1000)
      }
    }

    await checkAndWatch()

    return () => {
      isDisposed = true
      if (pollTimer) {
        clearTimeout(pollTimer)
        pollTimer = null
      }
      if (currentLogStream) {
        currentLogStream.destroy()
        currentLogStream = null
      }
    }
  }

  /**
   * Ensure docker image exists locally, pull if missing
   */
  async ensureImage(imageName: string): Promise<void> {
    try {
      const image = this.docker.getImage(imageName)
      await image.inspect()
    } catch (err: any) {
      if (err?.statusCode === 404) {
        const stream = await this.docker.pull(imageName)
        await new Promise<void>((resolve, reject) => {
          this.docker.modem.followProgress(stream, (pullErr: any) => {
            if (pullErr) return reject(pullErr)
            resolve()
          })
        })
      } else {
        throw err
      }
    }
  }

  protected diskUsageCache = new Map<number, { bytes: number; timestamp: number }>()

  /**
   * Calculate recursive directory size on disk in bytes
   */
  async calculateDirSize(dirPath: string): Promise<number> {
    try {
      let totalSize = 0
      const entries = await readdir(dirPath, { withFileTypes: true, recursive: true })
      for (const entry of entries) {
        if (entry.isFile()) {
          try {
            const parentDir = entry.parentPath || (entry as any).path || dirPath
            const entryPath = join(parentDir, entry.name)
            const fileStat = await stat(entryPath)
            totalSize += fileStat.size
          } catch {
            // Ignore transient file stat errors
          }
        }
      }
      return totalSize
    } catch {
      return 0
    }
  }

  /**
   * Get server data directory size on disk with 30s TTL cache
   */
  async getDiskBytes(server: McServer): Promise<number> {
    const cached = this.diskUsageCache.get(server.id)
    const now = Date.now()
    if (cached && now - cached.timestamp < 30_000) {
      return cached.bytes
    }

    const bytes = await this.calculateDirSize(server.dataDirectory)
    this.diskUsageCache.set(server.id, { bytes, timestamp: now })
    return bytes
  }

  /**
   * Fetch current hardware resource utilization metrics snapshot
   */
  async getContainerStats(server: McServer): Promise<ContainerStatsSnapshot> {
    const diskBytes = await this.getDiskBytes(server)
    const fallbackLimitBytes = server.maxMemoryMb * 1024 * 1024
    const defaultOfflineStats: ContainerStatsSnapshot = {
      online: false,
      cpuPercent: 0,
      memoryUsageBytes: 0,
      memoryBytes: 0,
      memoryLimitBytes: fallbackLimitBytes,
      memoryPercent: 0,
      networkRxBytes: 0,
      networkTxBytes: 0,
      diskBytes,
    }

    try {
      const container = this.getContainer(server)
      const inspect = await container.inspect()
      if (!inspect.State.Running) {
        return defaultOfflineStats
      }

      const stats: any = await container.stats({ stream: false })

      // Calculate CPU percent
      let cpuPercent = 0
      const cpuStats = stats.cpu_stats
      const preCpuStats = stats.precpu_stats
      if (cpuStats && preCpuStats) {
        const cpuDelta =
          (cpuStats.cpu_usage?.total_usage || 0) - (preCpuStats.cpu_usage?.total_usage || 0)
        const systemDelta = (cpuStats.system_cpu_usage || 0) - (preCpuStats.system_cpu_usage || 0)
        const onlineCpus = cpuStats.online_cpus || cpuStats.cpu_usage?.percpu_usage?.length || 1

        if (systemDelta > 0 && cpuDelta > 0) {
          const rawPercent = (cpuDelta / systemDelta) * onlineCpus * 100.0
          cpuPercent = Math.round(rawPercent * 100) / 100
        }
      }

      // Calculate Memory stats (subtract cache/inactive_file)
      const memStats = stats.memory_stats || {}
      const rawUsage = memStats.usage || 0
      const cache = memStats.stats?.inactive_file || memStats.stats?.cache || 0
      const memoryUsageBytes = Math.max(0, rawUsage - cache)
      const memoryLimitBytes = memStats.limit || fallbackLimitBytes
      const memoryPercent =
        memoryLimitBytes > 0 ? Math.round((memoryUsageBytes / memoryLimitBytes) * 10000) / 100 : 0

      // Calculate Network stats
      let networkRxBytes = 0
      let networkTxBytes = 0
      if (stats.networks) {
        for (const net of Object.values<any>(stats.networks)) {
          networkRxBytes += net.rx_bytes || 0
          networkTxBytes += net.tx_bytes || 0
        }
      }

      return {
        online: true,
        cpuPercent,
        memoryUsageBytes,
        memoryBytes: memoryUsageBytes,
        memoryLimitBytes,
        memoryPercent,
        networkRxBytes,
        networkTxBytes,
        diskBytes,
      }
    } catch (err: any) {
      if (err?.statusCode === 404) {
        return defaultOfflineStats
      }
      return defaultOfflineStats
    }
  }

  /**
   * Stream live container resource stats
   */
  async streamContainerStats(
    server: McServer,
    onStats: (stats: ContainerStatsSnapshot) => void
  ): Promise<() => void> {
    let active = true
    let timer: ReturnType<typeof setTimeout> | null = null

    const scheduleNext = () => {
      if (!active) return
      timer = setTimeout(async () => {
        if (!active) return
        try {
          const stats = await this.getContainerStats(server)
          if (active) {
            onStats(stats)
          }
        } catch {
          // Suppress transient collection errors
        } finally {
          if (active) {
            scheduleNext()
          }
        }
      }, 1500)
    }

    // Emit initial snapshot immediately
    try {
      const initial = await this.getContainerStats(server)
      if (active) {
        onStats(initial)
      }
    } catch {
      // Suppress transient initial error
    }

    scheduleNext()

    return () => {
      active = false
      if (timer) {
        clearTimeout(timer)
        timer = null
      }
    }
  }

  /**
   * Remove container if exists and release bound network ports
   */
  async removeContainer(server: McServer): Promise<void> {
    const removedIds = new Set<string>()

    // 1. Attempt direct removal by instance dedicated containerName
    try {
      const container = this.getContainer(server)
      const inspect = await container.inspect().catch(() => null)
      if (inspect) {
        removedIds.add(inspect.Id)
        await container.remove({ force: true, v: true })
      }
    } catch (err: any) {
      if (err?.statusCode !== 404 && err?.code !== 'ENOENT' && err?.code !== 'ECONNREFUSED') {
        logger.warn(`Failed direct container removal for server ${server.id}: ${err.message}`)
      }
    }

    // 2. Comprehensive scan: find and purge any lingering containers associated with
    // this instance (by identifier name variations or bound host port) to avoid port collisions
    try {
      const allContainers = await this.docker.listContainers({ all: true })
      const targetNames = [
        `/${server.containerName}`,
        `/pidan-mc-${server.identifier}`,
        `/pidan_mc_${server.identifier}`,
        server.containerName,
      ]

      for (const info of allContainers) {
        if (removedIds.has(info.Id)) {
          continue
        }

        const matchesName = (info.Names || []).some((n) => targetNames.includes(n))
        const matchesPort =
          (info.Names || []).some((n) => n.includes(server.identifier) || n.startsWith('/pidan')) &&
          (info.Ports || []).some((p) => p.PublicPort === server.serverPort)

        if (matchesName || matchesPort) {
          try {
            const lingeringContainer = this.docker.getContainer(info.Id)
            await lingeringContainer.remove({ force: true, v: true })
            removedIds.add(info.Id)
            logger.info(`Purged lingering container ${info.Id} occupying port ${server.serverPort}`)
          } catch (removeErr: any) {
            logger.warn(`Failed removing lingering container ${info.Id}: ${removeErr?.message}`)
          }
        }
      }
    } catch (scanErr: any) {
      if (scanErr?.code === 'ENOENT' || scanErr?.code === 'ECONNREFUSED') {
        logger.warn('Docker engine connection unavailable during container cleanup scan.')
      } else {
        logger.warn(`Docker container list scan error: ${scanErr?.message}`)
      }
    }
  }
}
