/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  McJarTypes: () => import('#controllers/mc_jar_types_controller'),
  McServers: () => import('#controllers/mc_servers_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  ServerBackupDownloads: () => import('#controllers/server_backup_downloads_controller'),
  ServerBackupRestorations: () => import('#controllers/server_backup_restorations_controller'),
  ServerBackups: () => import('#controllers/server_backups_controller'),
  ServerCommands: () => import('#controllers/server_commands_controller'),
  ServerFiles: () => import('#controllers/server_files_controller'),
  ServerJars: () => import('#controllers/server_jars_controller'),
  ServerLogs: () => import('#controllers/server_logs_controller'),
  ServerPowerStates: () => import('#controllers/server_power_states_controller'),
  ServerSchedules: () => import('#controllers/server_schedules_controller'),
  ServerStats: () => import('#controllers/server_stats_controller'),
  SystemStatus: () => import('#controllers/system_status_controller'),
  Users: () => import('#controllers/users_controller'),
}
