/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column()
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class McServerSchema extends BaseModel {
  static $columns = ['createdAt', 'dockerImage', 'id', 'identifier', 'javaArgs', 'maxMemoryMb', 'minMemoryMb', 'name', 'serverJar', 'serverPort', 'updatedAt'] as const
  $columns = McServerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dockerImage: string
  @column()
  declare id: number
  @column()
  declare identifier: string
  @column()
  declare javaArgs: string | null
  @column()
  declare maxMemoryMb: number
  @column()
  declare minMemoryMb: number
  @column()
  declare name: string
  @column()
  declare serverJar: string
  @column()
  declare serverPort: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'serverIds', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column()
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: 'admin' | 'user'
  @column()
  declare serverIds: number[]
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
