/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type McServerTransformer from '#transformers/mc_server_transformer'
import type ServerBackupTransformer from '#transformers/server_backup_transformer'
import type ServerFileTransformer from '#transformers/server_file_transformer'
import type ServerScheduleTransformer from '#transformers/server_schedule_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type McServer = InferData<McServerTransformer>
  export namespace McServer {
    export type Variants = InferVariants<McServerTransformer>
  }
  export type ServerBackup = InferData<ServerBackupTransformer>
  export namespace ServerBackup {
    export type Variants = InferVariants<ServerBackupTransformer>
  }
  export type ServerFile = InferData<ServerFileTransformer>
  export namespace ServerFile {
    export type Variants = InferVariants<ServerFileTransformer>
  }
  export type ServerSchedule = InferData<ServerScheduleTransformer>
  export namespace ServerSchedule {
    export type Variants = InferVariants<ServerScheduleTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
