import McServer from '#models/mc_server'
import User from '#models/user'
import {
  createMcServerValidator,
  updateMcServerValidator,
  deleteMcServerValidator,
} from '#validators/mc_server'
import McServerTransformer from '#transformers/mc_server_transformer'
import McContainerService from '#services/mc_container_service'
import ServerBackupService from '#services/server_backup_service'
import AuditLogService from '#services/audit_log_service'
import logger from '@adonisjs/core/services/logger'
import { inject } from '@adonisjs/core'
import type { HttpContext } from '@adonisjs/core/http'
import { mkdir, writeFile, rm } from 'node:fs/promises'
import { join } from 'node:path'

@inject()
export default class McServersController {
  constructor(
    protected containerService: McContainerService,
    protected backupService: ServerBackupService,
    protected auditLogService: AuditLogService
  ) {}

  /**
   * List all registered server instances (Admin sees all; Regular users see assigned only)
   */
  async index({ auth, serialize }: HttpContext) {
    const user = auth.user!
    const query = McServer.query().orderBy('id', 'asc')

    if (user.role !== 'admin') {
      const allowedIds = Array.isArray(user.serverIds) ? user.serverIds : []
      query.whereIn('id', allowedIds)
    }

    const servers = await query
    return serialize(McServerTransformer.transform(servers))
  }

  /**
   * Show single server details (Admin or authorized user)
   */
  async show({ params, auth, response, serialize }: HttpContext) {
    const user = auth.user!
    const server = await McServer.findOrFail(params.id)

    if (!user.hasServerAccess(server.id)) {
      return response.forbidden({
        errors: [{ message: 'Access denied to this server instance.' }],
      })
    }

    return serialize(McServerTransformer.transform(server))
  }

  /**
   * Create a new server instance (Admin only)
   */
  async store({ request, response, auth, serialize }: HttpContext) {
    const user = auth.user!
    if (user.role !== 'admin') {
      return response.forbidden({
        errors: [{ message: 'Only administrators can create server instances.' }],
      })
    }

    const payload = await request.validateUsing(createMcServerValidator)

    const minMem = payload.minMemoryMb ?? 1024
    const maxMem = payload.maxMemoryMb ?? 2048
    if (maxMem < minMem) {
      return response.badRequest({
        errors: [{ message: 'maxMemoryMb must be greater than or equal to minMemoryMb' }],
      })
    }

    const initBackoff = payload.crashBackoffInitialSeconds ?? 5
    const maxBackoff = payload.crashBackoffMaxSeconds ?? 300
    if (maxBackoff < initBackoff) {
      return response.badRequest({
        errors: [
          {
            message:
              'crashBackoffMaxSeconds must be greater than or equal to crashBackoffInitialSeconds',
          },
        ],
      })
    }

    const server = await McServer.create({
      stopTimeoutSeconds: 60,
      autoStartOnBoot: false,
      autoRestartOnCrash: false,
      crashBackoffInitialSeconds: 5,
      crashBackoffMaxSeconds: 300,
      crashMaxRetries: 5,
      ...payload,
    })

    // Initialize dedicated server data directory with eula.txt
    await mkdir(server.dataDirectory, { recursive: true })
    await writeFile(
      join(server.dataDirectory, 'eula.txt'),
      '# Generated by Pidan Panel\neula=true\n',
      'utf8'
    )

    await this.auditLogService.record({
      user,
      mcServer: server,
      category: 'server',
      action: 'server.create',
      details: {
        name: server.name,
        identifier: server.identifier,
        serverPort: server.serverPort,
      },
      status: 'success',
      ipAddress: request.ip(),
    })

    return response.created(await serialize(McServerTransformer.transform(server)))
  }

  /**
   * Update server configuration (Admin or authorized user)
   */
  async update({ params, request, response, auth, serialize }: HttpContext) {
    const user = auth.user!
    const server = await McServer.findOrFail(params.id)

    if (!user.hasServerAccess(server.id)) {
      return response.forbidden({
        errors: [{ message: 'Access denied to this server instance.' }],
      })
    }

    const payload = await request.validateUsing(updateMcServerValidator, {
      meta: { serverId: server.id },
    })

    const minMem = payload.minMemoryMb ?? server.minMemoryMb
    const maxMem = payload.maxMemoryMb ?? server.maxMemoryMb
    if (maxMem < minMem) {
      return response.badRequest({
        errors: [{ message: 'maxMemoryMb must be greater than or equal to minMemoryMb' }],
      })
    }

    const initBackoff = payload.crashBackoffInitialSeconds ?? server.crashBackoffInitialSeconds
    const maxBackoff = payload.crashBackoffMaxSeconds ?? server.crashBackoffMaxSeconds
    if (maxBackoff < initBackoff) {
      return response.badRequest({
        errors: [
          {
            message:
              'crashBackoffMaxSeconds must be greater than or equal to crashBackoffInitialSeconds',
          },
        ],
      })
    }

    // Check if server is running or restarting before modifying sensitive runtime properties (port)
    if (payload.serverPort !== undefined && payload.serverPort !== server.serverPort) {
      const runtime = await this.containerService.getContainerStatus(server)
      if (runtime.status === 'running' || runtime.status === 'restarting') {
        return response.conflict({
          errors: [
            {
              message:
                'Cannot modify server port while server is running. Please stop the server first.',
            },
          ],
        })
      }
    }

    // Only administrators may change the container image: assigned users
    // must not be able to pull and run arbitrary images with panel privileges.
    if (
      payload.dockerImage !== undefined &&
      user.role !== 'admin' &&
      payload.dockerImage !== server.dockerImage
    ) {
      return response.forbidden({
        errors: [{ message: 'Only administrators can change the container image.' }],
      })
    }

    const changedFields: string[] = []
    for (const key of Object.keys(payload) as (keyof typeof payload)[]) {
      if (payload[key] !== undefined) {
        changedFields.push(key)
      }
    }

    server.merge(payload)
    await server.save()

    await this.auditLogService.record({
      user,
      mcServer: server,
      category: 'server',
      action: 'server.update',
      details: {
        name: server.name,
        identifier: server.identifier,
        changedFields,
      },
      status: 'success',
      ipAddress: request.ip(),
    })

    return serialize(McServerTransformer.transform(server))
  }

  /**
   * Delete server instance (Admin only)
   */
  async destroy({ params, request, response, auth }: HttpContext) {
    const user = auth.user!
    if (user.role !== 'admin') {
      return response.forbidden({
        errors: [{ message: 'Only administrators can delete server instances.' }],
      })
    }

    const server = await McServer.findOrFail(params.id)

    // 1. Check if backup or restore is currently running for this server
    if (this.backupService.isInflight(server.id)) {
      return response.conflict({
        errors: [
          {
            message:
              'Cannot delete server while a backup or restore operation is in progress. Please wait for it to complete.',
          },
        ],
      })
    }

    // 2. Check if server container is active (running or restarting)
    const runtime = await this.containerService.getContainerStatus(server)
    if (runtime.status === 'running' || runtime.status === 'restarting') {
      return response.conflict({
        errors: [{ message: 'Cannot delete an active server. Please stop it first.' }],
      })
    }

    if (runtime.status === 'error') {
      return response.serviceUnavailable({
        errors: [
          {
            message:
              'Docker engine is unreachable. Cannot safely verify or remove the container, deletion aborted.',
          },
        ],
      })
    }

    const payload = await request.validateUsing(deleteMcServerValidator, {
      data: { deleteFiles: request.input('deleteFiles') },
    })
    const shouldDeleteFiles = payload.deleteFiles === true

    // 3. Purge instance snapshots (both on-disk archives and database records)
    await this.backupService.purgeInstanceBackups(server)

    // 4. Forcefully remove container(s) and unbind ports
    try {
      await this.containerService.removeContainer(server)
    } catch (error: any) {
      logger.error(`Container removal failed for server ${server.id}: ${error?.message}`)
      await this.auditLogService.record({
        user,
        mcServer: server,
        category: 'server',
        action: 'server.delete',
        details: {
          name: server.name,
          identifier: server.identifier,
          deleteFiles: shouldDeleteFiles,
        },
        status: 'failed',
        errorMessage: error?.message || 'Failed to remove the server container',
        ipAddress: request.ip(),
      })
      return response.internalServerError({
        errors: [
          { message: 'Failed to remove the server container. Deletion aborted, instance kept.' },
        ],
      })
    }

    // 5. Clean up assigned server permissions from all users
    const assignedUsers = await User.query().where('role', 'user')
    for (const u of assignedUsers) {
      if (Array.isArray(u.serverIds) && u.serverIds.includes(server.id)) {
        u.serverIds = u.serverIds.filter((sid) => sid !== server.id)
        await u.save()
      }
    }

    // 6. Wipe data directory if requested. Do this BEFORE removing the database
    // row so a failed wipe keeps the instance and allows a retry.
    if (shouldDeleteFiles) {
      try {
        await rm(server.dataDirectory, {
          recursive: true,
          force: true,
          maxRetries: 3,
          retryDelay: 100,
        })
      } catch (error: any) {
        logger.error(`Data directory wipe failed for server ${server.id}: ${error?.message}`)
        await this.auditLogService.record({
          user,
          mcServer: server,
          category: 'server',
          action: 'server.delete',
          details: {
            name: server.name,
            identifier: server.identifier,
            deleteFiles: true,
          },
          status: 'failed',
          errorMessage: error?.message || 'Failed to delete the server data directory',
          ipAddress: request.ip(),
        })
        return response.internalServerError({
          errors: [
            { message: 'Failed to delete the server files. Deletion aborted, instance kept.' },
          ],
        })
      }
    }

    await this.auditLogService.record({
      user,
      mcServer: server,
      category: 'server',
      action: 'server.delete',
      details: {
        name: server.name,
        identifier: server.identifier,
        deleteFiles: shouldDeleteFiles,
      },
      status: 'success',
      ipAddress: request.ip(),
    })

    await server.delete()

    return response.noContent()
  }
}
