import McServer from '#models/mc_server'
import User from '#models/user'
import { createMcServerValidator, updateMcServerValidator } from '#validators/mc_server'
import McServerTransformer from '#transformers/mc_server_transformer'
import McContainerService from '#services/mc_container_service'
import ServerBackupService from '#services/server_backup_service'
import { inject } from '@adonisjs/core'
import type { HttpContext } from '@adonisjs/core/http'
import { mkdir, writeFile, rm } from 'node:fs/promises'
import { join } from 'node:path'

@inject()
export default class McServersController {
  constructor(
    protected containerService: McContainerService,
    protected backupService: ServerBackupService
  ) {}

  /**
   * List all registered server instances (Admin sees all; Regular users see assigned only)
   */
  async index({ auth, serialize }: HttpContext) {
    const user = auth.user!
    const query = McServer.query().orderBy('id', 'asc')

    if (user.role !== 'admin') {
      const allowedIds = Array.isArray(user.serverIds) ? user.serverIds : []
      query.whereIn('id', allowedIds)
    }

    const servers = await query
    return serialize(McServerTransformer.transform(servers))
  }

  /**
   * Show single server details (Admin or authorized user)
   */
  async show({ params, auth, response, serialize }: HttpContext) {
    const user = auth.user!
    const server = await McServer.findOrFail(params.id)

    if (!user.hasServerAccess(server.id)) {
      return response.forbidden({
        errors: [{ message: 'Access denied to this server instance.' }],
      })
    }

    return serialize(McServerTransformer.transform(server))
  }

  /**
   * Create a new server instance (Admin only)
   */
  async store({ request, response, auth, serialize }: HttpContext) {
    const user = auth.user!
    if (user.role !== 'admin') {
      return response.forbidden({
        errors: [{ message: 'Only administrators can create server instances.' }],
      })
    }

    const payload = await request.validateUsing(createMcServerValidator)

    const minMem = payload.minMemoryMb ?? 1024
    const maxMem = payload.maxMemoryMb ?? 2048
    if (maxMem < minMem) {
      return response.badRequest({
        errors: [{ message: 'maxMemoryMb must be greater than or equal to minMemoryMb' }],
      })
    }

    const server = await McServer.create(payload)

    // Initialize dedicated server data directory with eula.txt
    await mkdir(server.dataDirectory, { recursive: true })
    await writeFile(
      join(server.dataDirectory, 'eula.txt'),
      '# Generated by Pidan Panel\neula=true\n',
      'utf8'
    )

    return response.created(await serialize(McServerTransformer.transform(server)))
  }

  /**
   * Update server configuration (Admin or authorized user)
   */
  async update({ params, request, response, auth, serialize }: HttpContext) {
    const user = auth.user!
    const server = await McServer.findOrFail(params.id)

    if (!user.hasServerAccess(server.id)) {
      return response.forbidden({
        errors: [{ message: 'Access denied to this server instance.' }],
      })
    }

    const payload = await request.validateUsing(updateMcServerValidator, {
      meta: { serverId: server.id },
    })

    const minMem = payload.minMemoryMb ?? server.minMemoryMb
    const maxMem = payload.maxMemoryMb ?? server.maxMemoryMb
    if (maxMem < minMem) {
      return response.badRequest({
        errors: [{ message: 'maxMemoryMb must be greater than or equal to minMemoryMb' }],
      })
    }

    // Check if server is running or restarting before modifying sensitive runtime properties (port)
    if (payload.serverPort !== undefined && payload.serverPort !== server.serverPort) {
      const runtime = await this.containerService.getContainerStatus(server)
      if (runtime.status === 'running' || runtime.status === 'restarting') {
        return response.conflict({
          errors: [
            {
              message:
                'Cannot modify server port while server is running. Please stop the server first.',
            },
          ],
        })
      }
    }

    server.merge(payload)
    await server.save()

    return serialize(McServerTransformer.transform(server))
  }

  /**
   * Delete server instance (Admin only)
   */
  async destroy({ params, request, response, auth }: HttpContext) {
    const user = auth.user!
    if (user.role !== 'admin') {
      return response.forbidden({
        errors: [{ message: 'Only administrators can delete server instances.' }],
      })
    }

    const server = await McServer.findOrFail(params.id)

    // 1. Check if backup or restore is currently running for this server
    if (this.backupService.isInflight(server.id)) {
      return response.conflict({
        errors: [
          {
            message:
              'Cannot delete server while a backup or restore operation is in progress. Please wait for it to complete.',
          },
        ],
      })
    }

    // 2. Check if server container is active (running or restarting)
    const runtime = await this.containerService.getContainerStatus(server)
    if (runtime.status === 'running' || runtime.status === 'restarting') {
      return response.conflict({
        errors: [{ message: 'Cannot delete an active server. Please stop it first.' }],
      })
    }

    const deleteFilesParam = request.input('deleteFiles')
    const shouldDeleteFiles =
      deleteFilesParam === true || deleteFilesParam === 'true' || deleteFilesParam === '1'

    // 3. Purge instance snapshots (both on-disk archives and database records)
    await this.backupService.purgeInstanceBackups(server)

    // 4. Forcefully remove container(s) and unbind ports
    await this.containerService.removeContainer(server)

    // 5. Clean up assigned server permissions from all users
    const assignedUsers = await User.query().where('role', 'user')
    for (const u of assignedUsers) {
      if (Array.isArray(u.serverIds) && u.serverIds.includes(server.id)) {
        u.serverIds = u.serverIds.filter((sid) => sid !== server.id)
        await u.save()
      }
    }

    // 6. Delete server database record
    await server.delete()

    // 7. Wipe data directory if requested
    if (shouldDeleteFiles) {
      await rm(server.dataDirectory, {
        recursive: true,
        force: true,
        maxRetries: 3,
        retryDelay: 100,
      }).catch(() => {})
    }

    return response.noContent()
  }
}
