import McServer from '#models/mc_server'
import { createMcServerValidator, updateMcServerValidator } from '#validators/mc_server'
import McServerTransformer from '#transformers/mc_server_transformer'
import McContainerService from '#services/mc_container_service'
import { inject } from '@adonisjs/core'
import type { HttpContext } from '@adonisjs/core/http'
import { mkdir, writeFile, rm } from 'node:fs/promises'
import { join } from 'node:path'

@inject()
export default class McServersController {
  constructor(protected containerService: McContainerService) {}

  /**
   * List all registered server instances (Admin sees all; Regular users see assigned only)
   */
  async index({ auth, serialize }: HttpContext) {
    const user = auth.user!
    const query = McServer.query().orderBy('id', 'asc')

    if (user.role !== 'admin') {
      const allowedIds = Array.isArray(user.serverIds) ? user.serverIds : []
      query.whereIn('id', allowedIds)
    }

    const servers = await query
    return serialize(McServerTransformer.transform(servers))
  }

  /**
   * Show single server details (Admin or authorized user)
   */
  async show({ params, auth, response, serialize }: HttpContext) {
    const user = auth.user!
    const server = await McServer.findOrFail(params.id)

    if (!user.hasServerAccess(server.id)) {
      return response.forbidden({
        errors: [{ message: 'Access denied to this server instance.' }],
      })
    }

    return serialize(McServerTransformer.transform(server))
  }

  /**
   * Create a new server instance (Admin only)
   */
  async store({ request, response, auth, serialize }: HttpContext) {
    const user = auth.user!
    if (user.role !== 'admin') {
      return response.forbidden({
        errors: [{ message: 'Only administrators can create server instances.' }],
      })
    }

    const payload = await request.validateUsing(createMcServerValidator)

    const minMem = payload.minMemoryMb ?? 1024
    const maxMem = payload.maxMemoryMb ?? 2048
    if (maxMem < minMem) {
      return response.badRequest({
        errors: [{ message: 'maxMemoryMb must be greater than or equal to minMemoryMb' }],
      })
    }

    const server = await McServer.create(payload)

    // Initialize dedicated server data directory with eula.txt
    await mkdir(server.dataDirectory, { recursive: true })
    await writeFile(
      join(server.dataDirectory, 'eula.txt'),
      '# Generated by Pidan Panel\neula=true\n',
      'utf8'
    )

    return response.created(await serialize(McServerTransformer.transform(server)))
  }

  /**
   * Update server configuration (Admin or authorized user)
   */
  async update({ params, request, response, auth, serialize }: HttpContext) {
    const user = auth.user!
    const server = await McServer.findOrFail(params.id)

    if (!user.hasServerAccess(server.id)) {
      return response.forbidden({
        errors: [{ message: 'Access denied to this server instance.' }],
      })
    }

    const payload = await request.validateUsing(updateMcServerValidator, {
      meta: { serverId: server.id },
    })

    const minMem = payload.minMemoryMb ?? server.minMemoryMb
    const maxMem = payload.maxMemoryMb ?? server.maxMemoryMb
    if (maxMem < minMem) {
      return response.badRequest({
        errors: [{ message: 'maxMemoryMb must be greater than or equal to minMemoryMb' }],
      })
    }

    // Check if server is running before modifying sensitive runtime properties (port)
    if (payload.serverPort !== undefined && payload.serverPort !== server.serverPort) {
      const runtime = await this.containerService.getContainerStatus(server)
      if (runtime.status === 'running') {
        return response.conflict({
          errors: [
            {
              message:
                'Cannot modify server port while server is running. Please stop the server first.',
            },
          ],
        })
      }
    }

    server.merge(payload)
    await server.save()

    return serialize(McServerTransformer.transform(server))
  }

  /**
   * Delete server instance (Admin only)
   */
  async destroy({ params, request, response, auth }: HttpContext) {
    const user = auth.user!
    if (user.role !== 'admin') {
      return response.forbidden({
        errors: [{ message: 'Only administrators can delete server instances.' }],
      })
    }

    const server = await McServer.findOrFail(params.id)

    const runtime = await this.containerService.getContainerStatus(server)
    if (runtime.status === 'running') {
      return response.conflict({
        errors: [{ message: 'Cannot delete a running server. Please stop it first.' }],
      })
    }

    const deleteFilesParam = request.input('deleteFiles')
    const shouldDeleteFiles =
      deleteFilesParam === true || deleteFilesParam === 'true' || deleteFilesParam === '1'

    await this.containerService.removeContainer(server)
    await server.delete()

    if (shouldDeleteFiles) {
      await rm(server.dataDirectory, { recursive: true, force: true }).catch(() => {})
    }

    return response.noContent()
  }
}
